AllCops:
  TargetRubyVersion: 2.6.2

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
Layout/DotPosition:
  EnforcedStyle: leading
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
Layout/IndentFirstArgument:
  EnforcedStyle: consistent
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 80000
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 80
  AllowURI: true
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/ClassCheck:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - 'context'
    - 'describe'
    - 'expect'
    - 'include'
    - 'it'
    - 'puts'
    - 'to'
    - 'require'
    - 'require_relative'
Style/RaiseArgs:
  Enabled: false
